context("Test CSESA functions")

test_that( "Test GetNewSpacerCode function", {
    spacer <- GetNewSpacer("GCGCCGGGAACACCAACGTCGGTTTATCCCCGCTGGCGCCGGGAACACAGGCGGACCGAAAAACCGTTTTCAGCCAACGTCGGTTTATCCCCGCTGGCGCCGGGAACACCAACGTCGGTTT")
    expect_equal(spacer, "AGGCGGACCGAAAAACCGTTTTCAGCCAACGT")

    spacerCode <- GetNewSpacerCode("GCGCCGGGAACACCAACGTCGGTTTATCCCCGCTGGCGCCGGGAACACAGGCGGACCGAAAAACCGTTTTCAGCCAACGTCGGTTTATCCCCGCTGGCGCCGGGAACACCAACGTCGGTTT")
    expect_equal(spacerCode, "Ent8")
})